language: cpp
compiler:
  - gcc
  - clang
  
install:
  - sudo apt-get update
  - sudo apt-get install cmake libqt4-dev libcups2-dev libsnappy-dev libpoppler-dev libpoppler-cpp-dev

script: 
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=Yes ..
  - make
  - xvfb-run gui/tests/boomaga_test 

